[project]
name = "trainer_bot"
version = "0.1.0"
description = "The Telegram-bot trainer project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    matplotlib==3.8.4,
    pyTelegramBotAPI==4.12.0
]
